"""ML and Chart tools for the DataWise toolkit.

Provides tools for retrieving ML analysis, chart data, and generating
new charts on demand.
"""
import os
import pandas as pd
import numpy as np
from typing import Any, Dict, List, Optional

from langchain_core.tools import tool

from backend.tools.dataframe_utils import (
    _get_dataframe,
    _validate_column,
    _format_value,
    _row_to_dict,
    _df_to_records,
)

_ALLOWED_CHART_TYPES = {
    "bar",
    "scatter",
    "line",
    "histogram",
    "box",
    "pie",
    "heatmap",
}


@tool
def get_ml_analysis(
    dataset_id: str,
) -> dict:
    """
    Get the validated machine-learning analysis produced for a dataset.
    Use this tool when the user asks about model performance, predictive
    relationships, important features, target prediction, model selection,
    classification/regression quality, or what variables are most useful for
    predicting the detected target.
    This returns evidence generated by DataWise's ML pipeline; it does not
    invent or estimate model metrics.
    """
    try:
        from backend.core.storage import analysis_repository

        record = analysis_repository.get(
            dataset_id.strip()
        )

        if record is None:
            return {
                "status": "unavailable",
                "reason": "Dataset session not found.",
            }

        ml_analysis = record.get("ml_analysis")

        if not ml_analysis:
            return {
                "status": "unavailable",
                "reason": (
                    "No ML analysis was stored for this dataset."
                ),
            }

        target_detection = (
            ml_analysis.get("target_detection")
            or {}
        )

        results = ml_analysis.get("results")

        if not results:
            return {
                "status": "skipped",
                "target": target_detection.get(
                    "target_column"
                ),
                "reason": (
                    "ML analysis was not run for this dataset."
                ),
            }

        return {
            "status": results.get(
                "status",
                "unknown",
            ),
            "target": target_detection.get(
                "target_column"
            ),
            "target_confidence": target_detection.get(
                "confidence",
                0,
            ),
            "problem_type": results.get(
                "problem_type"
            ),
            "data_modality": results.get(
                "data_modality"
            ),
            "selected_model": results.get(
                "selected_model"
            ),
            "fallback_model": results.get(
                "fallback_model"
            ),
            "used_fallback": results.get(
                "used_fallback",
                False,
            ),
            "selection_reason": results.get(
                "selection_reason",
                [],
            ),
            "model_confidence": results.get(
                "confidence",
                0,
            ),
            "metrics": results.get(
                "metrics",
                {},
            ),
            "feature_importance": results.get(
                "feature_importance",
                [],
            )[:20],
            "confusion_matrix": results.get(
                "confusion_matrix"
            ),
            "training_time_sec": results.get(
                "training_time_sec"
            ),
            "rows_used": results.get(
                "rows_used"
            ),
            "warnings": results.get(
                "warnings",
                [],
            ),
            "reason": results.get(
                "reason"
            ),
        }

    except Exception as e:
        return {
            "status": "error",
            "reason": (
                f"Failed to retrieve ML analysis: {e}"
            ),
        }


@tool
def get_chart_data(
    dataset_id: str,
    chart_index: Optional[int] = None,
) -> dict:
    """
    Get the data and metadata for a chart generated during analysis.
    Args:
        dataset_id: The session/dataset identifier
        chart_index: Optional specific chart index (0-based).
                     If not provided, returns the most recent chart.
    Use this when the user asks to explain, describe, or interpret a chart.
    """
    try:
        from backend.core.storage import analysis_repository

        record = analysis_repository.get(
            dataset_id.strip()
        )

        if record is None:
            return {
                "status": "unavailable",
                "reason": "Dataset session not found.",
            }

        chart_data_list = record.get(
            "chartData",
            []
        )

        chart_paths = record.get(
            "chart_paths",
            []
        )

        if not chart_data_list:
            return {
                "status": "unavailable",
                "reason": (
                    "No charts were generated for this dataset."
                ),
            }

        if chart_index is None:
            chart_index = len(chart_data_list) - 1

        if (
            chart_index < 0
            or chart_index >= len(chart_data_list)
        ):
            return {
                "status": "error",
                "reason": (
                    "Invalid chart index. Available: "
                    f"0-{len(chart_data_list) - 1}"
                ),
            }

        chart = chart_data_list[chart_index]

        chart_path = (
            chart_paths[chart_index]
            if chart_index < len(chart_paths)
            else None
        )

        return {
            "status": "success",
            "chart_index": chart_index,
            "total_charts": len(chart_data_list),
            "chart": chart,
            "image_path": chart_path,
            "available_charts": [
                {
                    "index": i,
                    "title": c.get(
                        "title",
                        f"Chart {i}",
                    ),
                    "type": c.get(
                        "type",
                        "unknown",
                    ),
                }
                for i, c in enumerate(chart_data_list)
            ],
        }

    except Exception as e:
        return {
            "status": "error",
            "reason": (
                f"Failed to retrieve chart data: {e}"
            ),
        }


@tool
def generate_chart(
    dataset_id: str,
    chart_type: str,
    x_axis: str,
    y_axis: Optional[str] = None,
    title: Optional[str] = None,
    x_label: Optional[str] = None,
    y_label: Optional[str] = None,
) -> dict:
    """
    Generate a NEW chart on demand and APPEND it to the dataset's existing charts.
    Use this when the user asks to draw / plot / create a specific chart that is
    not already in the analysis (e.g. "draw a histogram of age", "plot sales vs time").
    Do NOT use this to explain an existing chart — use get_chart_data for that.

    Special ML charts (synthetic axes — not real dataframe columns):
    - Feature importance: chart_type="bar", x_axis="feature", y_axis="importance"
    - Confusion matrix: chart_type="heatmap", x_axis="predicted", y_axis="actual"
    - Actual vs predicted: chart_type="scatter", x_axis="actual", y_axis="predicted"
    - Residuals: chart_type="histogram", x_axis="residual"

    Args:
        dataset_id: The session/dataset identifier.
        chart_type: One of: bar, scatter, line, histogram, box, pie, heatmap.
        x_axis: Column name, OR a special ML axis (feature / actual / residual).
        y_axis: Optional column name, OR importance / predicted for ML charts.
        title: Optional chart title. Auto-generated if omitted.
        x_label: Optional x-axis label (defaults to x_axis).
        y_label: Optional y-axis label (defaults to y_axis).
    """
    try:
        from backend.core.storage import analysis_repository
        from backend.core.state import AgentState
        from backend.models.chart import ChartConfig
        from backend.models.plan import Plan
        from backend.agents.visualization.viz_agent import VisualizationAgent
        from backend.ml.schemas import MLResults

        dataset_id = (dataset_id or "").strip()
        if not dataset_id:
            return {"status": "error", "reason": "dataset_id is required."}

        chart_type = (chart_type or "").strip().lower()
        if chart_type not in _ALLOWED_CHART_TYPES:
            return {
                "status": "error",
                "reason": (
                    f"Unsupported chart_type '{chart_type}'. "
                    f"Allowed: {sorted(_ALLOWED_CHART_TYPES)}"
                ),
            }

        x_axis = (x_axis or "").strip()
        if not x_axis and chart_type != "heatmap":
            return {
                "status": "error",
                "reason": "x_axis is required for this chart type.",
            }

        record = analysis_repository.get(dataset_id)
        if record is None:
            return {
                "status": "unavailable",
                "reason": "Dataset session not found.",
            }

        df_path = record.get("df_path")
        if not df_path or not os.path.exists(df_path):
            return {
                "status": "error",
                "reason": f"Dataset file not found at: {df_path}",
            }

        df = _get_dataframe(df_path)

        # ML synthetic axes — not real dataframe columns.
        _ML_AXES = {
            "feature",
            "importance",
            "actual",
            "predicted",
            "residual",
        }
        is_ml_chart = (
            x_axis in _ML_AXES
            or (y_axis or "") in _ML_AXES
            or (
                chart_type == "heatmap"
                and x_axis in {"", "predicted", "actual"}
            )
        )

        # Validate columns exist (heatmap / ML charts may skip real columns).
        if chart_type != "heatmap" and not is_ml_chart:
            if x_axis not in df.columns:
                return {
                    "status": "error",
                    "reason": (
                        f"Column '{x_axis}' not found. "
                        f"Available: {list(df.columns)}"
                    ),
                }
            if y_axis and y_axis not in df.columns:
                return {
                    "status": "error",
                    "reason": (
                        f"Column '{y_axis}' not found. "
                        f"Available: {list(df.columns)}"
                    ),
                }

        # Hydrate ML results so VisualizationAgent can render ML charts.
        ml_results = None
        ml_raw = (record.get("ml_analysis") or {}).get("results")
        if isinstance(ml_raw, dict):
            try:
                ml_results = MLResults.model_validate(ml_raw)
            except Exception:
                ml_results = None

        if is_ml_chart and (
            ml_results is None or ml_results.status != "success"
        ):
            return {
                "status": "error",
                "reason": (
                    "This chart needs ML analysis results, but none are "
                    "available for this dataset."
                ),
            }

        existing_chart_data = list(record.get("chartData") or [])
        existing_paths = list(record.get("chart_paths") or [])
        existing_charts = list(record.get("charts") or [])
        next_index = len(existing_paths) + 1
        final_path = f"chart_{next_index}.png"

        resolved_title = title or (
            f"{chart_type.title()}: {x_axis}"
            + (f" vs {y_axis}" if y_axis else "")
        )
        resolved_x_label = x_label or x_axis or ""
        resolved_y_label = y_label or y_axis

        chart_config = ChartConfig(
            chart_type=chart_type,  # type: ignore[arg-type]
            x_axis=x_axis or "",
            y_axis=y_axis,
            title=resolved_title,
            x_label=resolved_x_label,
            y_label=resolved_y_label,
        )
        plan = Plan(
            steps=["Generate on-demand chart from chat"],
            requires_cleaning=False,
            charts=[chart_config],
            requires_report=False,
        )

        session_dir = os.path.dirname(df_path)
        target_detection = (
            record.get("target_detection")
            or (record.get("ml_analysis") or {}).get("target_detection")
            or {}
        )
        state = AgentState(
            session_id=dataset_id,
            session_dir=session_dir,
            file_path=df_path,
            user_query=resolved_title,
            df_path=df_path,
            plan=plan,
            ml_results=ml_results,
            target_detection=target_detection,
        )

        # VizAgent always writes session_dir/chart_0.png for a single-chart
        # plan. That would destroy the existing analysis chart_0.png, so we
        # back it up first, then move the new image to chart_{next_index}.png
        # and restore the original chart_0.png.
        import shutil

        chart0_path = os.path.join(session_dir, "chart_0.png")
        chart0_backup = os.path.join(session_dir, "chart_0.png.__bak__")
        backed_up_chart0 = False
        if next_index > 0 and os.path.exists(chart0_path):
            shutil.copy2(chart0_path, chart0_backup)
            backed_up_chart0 = True

        try:
            viz_agent = VisualizationAgent()
            result_state = viz_agent.run(state)

            new_paths = list(result_state.visualization_paths or [])
            new_visualizations = list(result_state.visualizations or [])

            if not new_paths or not new_visualizations:
                skipped = getattr(result_state, "skipped_charts", None) or []
                reason = "VisualizationAgent produced no chart."
                if skipped:
                    reason = skipped[0].get("reason", reason)
                return {
                    "status": "error",
                    "reason": reason,
                    "skipped_charts": skipped,
                }

            produced_path = new_paths[0]
            final_path = os.path.join(session_dir, f"chart_{next_index}.png")

            if not os.path.exists(produced_path):
                return {
                    "status": "error",
                    "reason": (
                        f"Chart image was not written to disk: {produced_path}"
                    ),
                }

            if os.path.abspath(produced_path) != os.path.abspath(final_path):
                if os.path.exists(final_path):
                    os.remove(final_path)
                shutil.move(produced_path, final_path)
            # else: next_index == 0 — first chart ever; keep chart_0.png as-is

            # Restore original chart_0.png after moving the new image away.
            if backed_up_chart0 and os.path.exists(chart0_backup):
                shutil.move(chart0_backup, chart0_path)
                backed_up_chart0 = False

        finally:
            # If anything failed mid-way, still try to restore chart_0.
            if backed_up_chart0 and os.path.exists(chart0_backup):
                try:
                    shutil.move(chart0_backup, chart0_path)
                except OSError:
                    pass

        new_viz = dict(new_visualizations[0])
        new_viz["id"] = next_index

        existing_paths.append(final_path)
        existing_chart_data.append(new_viz)
        existing_charts.append({
            "id": next_index,
            "url": f"/datasets/{dataset_id}/charts/{next_index}",
        })

        # Persist full record with appended charts (do not wipe other fields).
        updated = {
            k: v for k, v in record.items() if k != "status"
        }
        updated["chartData"] = existing_chart_data
        updated["chart_paths"] = existing_paths
        updated["charts"] = existing_charts
        analysis_repository.complete(dataset_id, updated)

        return {
            "status": "success",
            "chart_index": next_index,
            "total_charts": len(existing_paths),
            "chart": new_viz,
            "image_path": final_path,
            "available_charts": [
                {
                    "index": i,
                    "title": c.get("title", f"Chart {i}"),
                    "type": c.get("type", "unknown"),
                }
                for i, c in enumerate(existing_chart_data)
            ],
        }

    except Exception as e:
        return {
            "status": "error",
            "reason": f"Failed to generate chart: {e}",
        }